val mouse_goal_orientation : Types.animal -> float (*returns the relative orientation of the mouse to the goal*)
val relative_animal_orientation : Types.animal -> Types.animal -> float (*returns the relative orientation of an animal to another*)
val h1_cat : Types.game -> float (*returns a value calculated according to the distance of the cat to the mouse*)
val h2_cat : Types.game -> float (*returns a value calculated according to the distance of the cat to the half-point of the segment between mouse and goal*)
val h3_cat : Types.game -> float (*returns a value calculated according to the distance of the mouse to the goal*)
val h4_cat : Types.game -> float (*returns a value calculated according to the result of h2_cat and h3_cat*)
val h5_cat : Types.game -> float (*returns a value calculated according to the result of h2_cat and h3_cat*)
val h6_cat : Types.game -> float (*returns a value calculated according to the result of h1_cat, h2_cat and h3_cat*)
val h1_mouse : Types.game -> float (*returns a value calculated according to the distance of the mouse to the goal*)
val h2_mouse : Types.game -> float (*returns a value calculated according to the distance of the cat to the mouse*)
val h3_mouse : Types.game -> float (*returns a value calculated according to the result of h1_mouse and h2_mouse*)
val h4_mouse : Types.game -> float (*returns a value calculated according to the result of h1_mouse, h2_mouse and the orientation of the mouse towards the goal*)
val heuristic_match : Types.game -> int -> float (*returns the heuristic associated with a value*)
